language: node_js
node_js:
  - v8
  - v6
  - v5
  - v4

sudo: false

services:
  - docker

before_install:
  - docker-compose -f ./docker-compose.dev.yml up -d

cache:
  directories:
    - node_modules

before_script:  
  - "gulp config-mysql"
  - "./node_modules/sequelize-cli/bin/sequelize db:migrate"
  - "gulp config-psql"
  - "./node_modules/sequelize-cli/bin/sequelize db:migrate"

script: "gulp"