language: node_js
node_js:
  - v5
  - v4

sudo: false

cache:
  directories:
    - node_modules

before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "gulp config"
  - "cd test && ../node_modules/sequelize-cli/bin/sequelize db:migrate"

script: "gulp"