# PostgreSQL test database
postgres:
  container_name: sequelize_models_pg
  image: postgres
  env_file:
    - ./.env
  ports:
    - "5438:5432"


# MySQL test database
mysql:
  container_name: sequelize_models_mysql
  image: mysql:5.6
  volumes:
      - ./mysql.conf:/etc/my.cnf
  env_file:
    - ./.env
  ports:
    - "3308:3306"